tenant: tenant-name
github:
  token: ghp_qwerty
  organization: coreeng-dev

repositories:
  dplatform: /path/to/dplatform-environments
  templates: /path/to/software-templates

p2p:
  fast-feedback:
    default-envs:
      - gcp-dev
  extended-test:
    default-envs:
      - gcp-dev
  prod:
    default-envs:
      - gpc-prod
