name: Fast Feedback
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOPRIVATE: github.com/coreeng
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: go-private-module-access
        run: |
          git config --global url."https://${GH_ACCESS_TOKEN}@github.com/coreeng".insteadOf "https://github.com/coreeng"
          go mod download
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=3m
      - name: test
        run: |
          git config --global user.name "Test Bot"
          git config --global user.email "test@bot.com"
          make test
  integration-test:
    runs-on: ubuntu-24.04
    name: Integration Test
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go-private-module-access
        run: |
          git config --global url."https://${GH_ACCESS_TOKEN}@github.com/coreeng".insteadOf "https://github.com/coreeng"
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: integration-test
        run: |
          git config --global user.name "Test Bot"
          git config --global user.email "test@bot.com"
          make integration-test
        env:
          GITHUB_TOKEN: ${{ secrets.INTEGRATION_TEST_GH_TOKEN }}
