name: foo Fast Feedback

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - foo/**
  pull_request:
    branches:
      - main
    paths:
      - foo/**

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: foo/v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    
  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    with:
      version: ${{ needs.version.outputs.version }}
      working-directory: foo