name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  GOPRIVATE: github.com/coreeng
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Create release
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: go-private-module-access
        run: |
          git config --global url."https://${GH_ACCESS_TOKEN}@github.com/coreeng".insteadOf "https://github.com/coreeng"
      - name: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: go-releaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
